# -*- coding: utf-8 -*-
"""Legacy figures: model gradient, E5 self-consistency distribution, triage scatter.
The paper's figures are generated by make_figures_pub.py; this script is kept for reference."""
import json, os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from common import find_violations, disjoint_lower_bound, validate_against_gold, gold_error_records, TYPES, norm, NAME2PID, ROOT
from analyze_resample import analyze_model as analyze_recurrence

plt.rcParams.update({"font.size": 11, "figure.dpi": 150, "savefig.bbox": "tight",
                     "axes.spines.top": False, "axes.spines.right": False})
FIG = os.path.join(ROOT, "result", "figs")
os.makedirs(FIG, exist_ok=True)
DOCS = json.load(open(os.path.join(ROOT, "data", "redocred_dev_300.json")))
SIGS = json.load(open(os.path.join(ROOT, "data", "relations.json")))
MODELS = ["Qwen/Qwen2.5-7B-Instruct", "Qwen/Qwen2.5-14B-Instruct", "Qwen/Qwen2.5-32B-Instruct",
          "Qwen/Qwen2.5-72B-Instruct", "deepseek-ai/DeepSeek-V3"]
LABELS = ["Qwen2.5\n7B", "Qwen2.5\n14B", "Qwen2.5\n32B", "Qwen2.5\n72B", "DeepSeek\nV3"]
safe = lambda m: m.replace("/", "__")


def per_model():
    rows = []
    for m in MODELS:
        valid = fired = ndoc = viol = sound = 0
        for i in range(len(DOCS)):
            p = os.path.join(ROOT, "result", "extractions", safe(m), f"{i:04d}.json")
            if not os.path.exists(p):
                continue
            ndoc += 1
            try:
                ext = json.load(open(p))
            except Exception:
                continue
            ents = [e for e in ext.get("entities", []) if isinstance(e, dict) and e.get("type") in TYPES]
            if not ents and not ext.get("relations"):
                continue
            valid += 1
            vs, et = find_violations(ext, SIGS, "empirical")
            vs, _ = validate_against_gold(vs, et, DOCS[i])
            b = disjoint_lower_bound([v["he"] for v in vs])
            fired += (b > 0)
            chk = [v for v in vs if v["checkable"]]
            viol += len(chk); sound += sum(1 for v in chk if v["sound"])
        rows.append(dict(valid=valid / ndoc, fired=fired / max(valid, 1),
                         sound=(sound / viol if viol else 1.0)))
    return rows


# Fig 2: model gradient
rows = per_model()
x = np.arange(len(MODELS)); w = 0.38
fig, ax = plt.subplots(figsize=(7.2, 3.6))
ax.bar(x - w / 2, [r["valid"] * 100 for r in rows], w, label="Valid-JSON rate", color="#4C72B0")
ax.bar(x + w / 2, [r["fired"] * 100 for r in rows], w, label="Certificate firing rate", color="#DD8452")
for i, r in enumerate(rows):
    if r["fired"] > 0:
        ax.text(i + w / 2, r["fired"] * 100 + 1.5, f"snd\n100%", ha="center", va="bottom", fontsize=7.5, color="#2a7")
ax.set_xticks(x); ax.set_xticklabels(LABELS)
ax.set_ylabel("%"); ax.set_ylim(0, 105)
ax.set_title("Certificate across the model-capability gradient (gold validation=100% throughout)")
ax.legend(loc="center right", frameon=False, fontsize=9)
plt.savefig(os.path.join(FIG, "fig2_gradient.pdf")); plt.savefig(os.path.join(FIG, "fig2_gradient.png")); plt.close()
print("fig2 ok", [(round(r['valid'],2), round(r['fired'],2), round(r['sound'],3)) for r in rows])

# Fig 3: E5 self-consistency distribution under the unique visible-error unit.
MODEL = "Qwen/Qwen2.5-32B-Instruct"; K = 5
sc_summary, _ = analyze_recurrence(MODEL, 50, K)
counts = [sc_summary[f"recurrence_{f}"] for f in range(K + 1)]
fig, ax = plt.subplots(figsize=(6.4, 3.4))
colors = ["#BBB", "#BBB", "#BBB", "#C44", "#C44", "#C44"]
ax.bar(range(K + 1), counts, color=colors)
ax.set_xlabel(f"Recurrence of a visible error item\n(times it recurs across K={K} stochastic decodes)")
ax.set_ylabel("# visible error items")
hi = sc_summary["stable_visible_errors"]; total = sc_summary["certificate_visible_errors"]
ax.set_title(f"{hi}/{total}={hi/total:.0%} of visible errors are stable (>=3/5)\n"
             f"-> a recurrence alarm misses them (red)")
plt.savefig(os.path.join(FIG, "fig3_selfconsistency.pdf")); plt.savefig(os.path.join(FIG, "fig3_selfconsistency.png")); plt.close()
print("fig3 ok, dist", counts, "hi%", round(hi/total,2))

# Fig 4: triage scatter
def true_err(ext, d):
    return len(gold_error_records(ext, d)["errors"])

M2 = "deepseek-ai/DeepSeek-V3"; bs, es = [], []
for i in range(len(DOCS)):
    p = os.path.join(ROOT, "result", "extractions", safe(M2), f"{i:04d}.json")
    if not os.path.exists(p):
        continue
    ext = json.load(open(p))
    if ext.get("_error"):
        continue
    vs, et = find_violations(ext, SIGS, "empirical"); vs, _ = validate_against_gold(vs, et, DOCS[i])
    bs.append(disjoint_lower_bound([v["he"] for v in vs])); es.append(true_err(ext, DOCS[i]))
rx = np.argsort(np.argsort(bs)); ry = np.argsort(np.argsort(es)); rho = np.corrcoef(rx, ry)[0, 1]
fig, ax = plt.subplots(figsize=(5.4, 3.6))
jit = lambda a: np.array(a) + np.random.RandomState(0).uniform(-0.15, 0.15, len(a))
ax.scatter(jit(bs), es, s=18, alpha=0.5, color="#4C72B0")
ax.set_xlabel("Certificate lower bound (per document)"); ax.set_ylabel("True error count (vs gold)")
ax.set_title(f"Certificate bound vs. true errors — DeepSeek-V3 (Spearman rho={rho:.2f})")
plt.savefig(os.path.join(FIG, "fig4_triage.pdf")); plt.savefig(os.path.join(FIG, "fig4_triage.png")); plt.close()
print("fig4 ok rho", round(rho,3))
print("figures written to", FIG)
